server:
  port: 8080


spring:
  application:
    name: "message-router"

  kafka:
    bootstrap-servers: kafka:9092
    topic: topic-1
    consumer:
      client-id: message-router
      group-id: group-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres

    liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  info:
    title: "Message Router API"
    description: "API documentation for the Message application"
    version: "1.0.0"

kafka-listener:
  groups:
    message:
      group-id: message
      concurrency: 3
    alerting:
      group-id: alerting
      concurrency: 2
    notification:
      group-id: notification
      concurrency: 4

